EMOTICONS = {
    ':‐)': 'Happy face or smiley', ':-))': 'Very happy', ':-)))': 'Very very Happy face or smiley',
    ':)': 'Happy face or smiley', ':))': 'Very Happy face or smiley', ':)))': 'Very very Happy face or smiley',
    ':-]': 'Happy face or smiley', ':]': 'Happy face or smiley', ':-3': 'Happy face smiley',
    ':3': 'Happy face smiley',
    ':->': 'Happy face smiley', ':>': 'Happy face smiley', '8-)': 'Happy face smiley',
    ':o)': 'Happy face smiley',
    ':-}': 'Happy face smiley', ':}': 'Happy face smiley', ':-)': 'Happy face smiley',
    ':c)': 'Happy face smiley',
    ':^)': 'Happy face smiley', '=]': 'Happy face smiley', '=)': 'Happy face smiley',
    ':‐D': 'Laughing, big grin or laugh with glasses', ':D': 'Laughing, big grin or laugh with glasses',
    '8‐D': 'Laughing, big grin or laugh with glasses', '8D': 'Laughing, big grin or laugh with glasses',
    'X‐D': 'Laughing, big grin or laugh with glasses', 'XD': 'Laughing, big grin or laugh with glasses',
    '=D': 'Laughing, big grin or laugh with glasses', '=3': 'Laughing, big grin or laugh with glasses',
    'B^D': 'Laughing, big grin or laugh with glasses', ':-(': 'Frown, sad, andry or pouting',
    ':‐(': 'Frown, sad, andry or pouting', ':(': 'Frown, sad, andry or pouting',
    ':‐c': 'Frown, sad, andry or pouting',
    ':c': 'Frown, sad, andry or pouting', ':‐<': 'Frown, sad, andry or pouting',
    ':<': 'Frown, sad, andry or pouting',
    ':‐[': 'Frown, sad, andry or pouting', ':[': 'Frown, sad, andry or pouting',
    ':-||': 'Frown, sad, andry or pouting',
    '>:[': 'Frown, sad, andry or pouting', ':{': 'Frown, sad, andry or pouting',
    ':@': 'Frown, sad, andry or pouting',
    '>:(': 'Frown, sad, andry or pouting', ":'‐(": 'Crying', ":'(": 'Crying', ":'‐)": 'Tears of happiness',
    ":')": 'Tears of happiness', "D‐':": 'Horror', 'D:<': 'Disgust', 'D:': 'Sadness', 'D8': 'Great dismay',
    'D;': 'Great dismay', 'D=': 'Great dismay', 'DX': 'Great dismay', ':‐O': 'Surprise', ':O': 'Surprise',
    ':‐o': 'Surprise', ':o': 'Surprise', ':-0': 'Shock', '8‐0': 'Yawn', '>:O': 'Yawn', ':-*': 'Kiss',
    ':*': 'Kiss',
    ':X': 'Kiss', ';‐)': 'Wink or smirk', ';)': 'Wink or smirk', '*-)': 'Wink or smirk', '*)': 'Wink or smirk',
    ';‐]': 'Wink or smirk', ';]': 'Wink or smirk', ';^)': 'Wink or smirk', ':‐,': 'Wink or smirk',
    ';D': 'Wink or smirk',
    ':‐P': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    ':P': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    'X‐P': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    'XP': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    ':‐Þ': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    ':Þ': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    ':b': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    'd:': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    '=p': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    '>:P': 'Tongue sticking out, cheeky, playful or blowing a raspberry',
    ':‐/': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    ':/': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    ':-[.]': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    '>:[(\\)]': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    '>:/': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    ':[(\\)]': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    '=/': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    '=[(\\)]': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    ':L': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    '=L': 'Skeptical, annoyed, undecided, uneasy or hesitant',
    ':S': 'Skeptical, annoyed, undecided, uneasy or hesitant', ':‐|': 'Straight face', ':|': 'Straight face',
    ':$': 'Embarrassed or blushing', ':‐x': 'Sealed lips or wearing braces or tongue-tied',
    ':x': 'Sealed lips or wearing braces or tongue-tied',
    ':‐#': 'Sealed lips or wearing braces or tongue-tied',
    ':#': 'Sealed lips or wearing braces or tongue-tied',
    ':‐&': 'Sealed lips or wearing braces or tongue-tied',
    ':&': 'Sealed lips or wearing braces or tongue-tied', 'O:‐)': 'Angel, saint or innocent',
    'O:)': 'Angel, saint or innocent', '0:‐3': 'Angel, saint or innocent', '0:3': 'Angel, saint or innocent',
    '0:‐)': 'Angel, saint or innocent', '0:)': 'Angel, saint or innocent',
    ':‐b': 'Tongue sticking out, cheeky, playful or blowing a raspberry', '0;^)': 'Angel, saint or innocent',
    '>:‐)': 'Evil or devilish', '>:)': 'Evil or devilish', '}:‐)': 'Evil or devilish',
    '}:)': 'Evil or devilish',
    '3:‐)': 'Evil or devilish', '3:)': 'Evil or devilish', '>;)': 'Evil or devilish', '|;‐)': 'Cool',
    '|‐O': 'Bored',
    ':‐J': 'Tongue-in-cheek', '#‐)': 'Party all night', '%‐)': 'Drunk or confused', '%)': 'Drunk or confused',
    ':-###..': 'Being sick', ':###..': 'Being sick', '<:‐|': 'Dump', '(>_<)': 'Troubled', '(>_<)>': 'Troubled',
    "(';')": 'Baby', '(^^>``': 'Nervous or Embarrassed or Troubled or Shy or Sweat drop',
    '(^_^;)': 'Nervous or Embarrassed or Troubled or Shy or Sweat drop',
    '(-_-;)': 'Nervous or Embarrassed or Troubled or Shy or Sweat drop',
    '(~_~;) (・.・;)': 'Nervous or Embarrassed or Troubled or Shy or Sweat drop', '(-_-)zzz': 'Sleeping',
    '(^_-)': 'Wink',
    '((+_+))': 'Confused', '(+o+)': 'Confused', '(o|o)': 'Ultraman', '^_^': 'Joyful', '(^_^)/': 'Joyful',
    '(^O^)/': 'Joyful', '(^o^)/': 'Joyful', '(__)': 'Kowtow as a sign of respect, or dogeza for apology',
    '_(._.)_': 'Kowtow as a sign of respect, or dogeza for apology',
    '<(_ _)>': 'Kowtow as a sign of respect, or dogeza for apology',
    '<m(__)m>': 'Kowtow as a sign of respect, or dogeza for apology',
    'm(__)m': 'Kowtow as a sign of respect, or dogeza for apology',
    'm(_ _)m': 'Kowtow as a sign of respect, or dogeza for apology', "('_')": 'Sad or Crying',
    '(/_;)': 'Sad or Crying',
    '(T_T) (;_;)': 'Sad or Crying', '(;_;': 'Sad of Crying', '(;_:)': 'Sad or Crying',
    '(;O;)': 'Sad or Crying',
    '(:_;)': 'Sad or Crying', '(ToT)': 'Sad or Crying', ';_;': 'Sad or Crying', ';-;': 'Sad or Crying',
    ';n;': 'Sad or Crying', ';;': 'Sad or Crying', 'Q.Q': 'Sad or Crying', 'T.T': 'Sad or Crying',
    'QQ': 'Sad or Crying',
    'Q_Q': 'Sad or Crying', '(-.-)': 'Shame', '(-_-)': 'Shame', '(一一)': 'Shame', '(;一_一)': 'Shame',
    '(=_=)': 'Tired',
    '(=^·^=)': 'cat', '(=^··^=)': 'cat', '=_^= ': 'cat', '(..)': 'Looking down', '(._.)': 'Looking down',
    '^m^': 'Giggling with hand covering mouth', '(・・?': 'Confusion', '(?_?)': 'Confusion',
    '>^_^<': 'Normal Laugh',
    '<^!^>': 'Normal Laugh', '^/^': 'Normal Laugh', '(*^_^*)': 'Normal Laugh', '(^<^) (^.^)': 'Normal Laugh',
    '(^^)': 'Normal Laugh', '(^.^)': 'Normal Laugh', '(^_^.)': 'Normal Laugh', '(^_^)': 'Normal Laugh',
    '(^J^)': 'Normal Laugh', '(*^.^*)': 'Normal Laugh', '(^—^)': 'Waving', '(#^.^#)': 'Normal Laugh',
    '(;_;)/~~~': 'Waving', '(^.^)/~~~': 'Waving', '(-_-)/~~~ ($··)/~~~': 'Waving', '(T_T)/~~~': 'Waving',
    '(ToT)/~~~': 'Waving', '(*^0^*)': 'Excited', '(*_*)': 'Amazed', '(*_*;': 'Amazed', '(+_+) (@_@)': 'Amazed',
    '(*^^)v': 'Laughing,Cheerful', '(^_^)v': 'Laughing,Cheerful',
    '((d[-_-]b))': 'Headphones,Listening to music',
    '(-"-)': 'Worried', '(ーー;)': 'Worried', '(^0_0^)': 'Eyeglasses', '(^v^)': 'Happy', '(^u^)': 'Happy',
    '(^)o(^)': 'Happy', '(^O^)': 'Happy', '(^o^)': 'Happy', ')^o^(': 'Happy', ':O o_O': 'Surprised',
    'o_0': 'Surprised',
    'o.O': 'Surpised', '(o.o)': 'Surprised', 'oO': 'Surprised', '(* ̄m ̄)': 'Dissatisfied',
    '(‘A`)': 'Snubbed or Deflated',
    '<3': 'heart'}
